name = "Gemini 3.1 Pro Preview (batch)"
family = "gemini"
release_date = "2026-02-19"
last_updated = "2026-02-19"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1
output = 6
reasoning = 6

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["audio", "pdf", "image", "text", "video"]
output = ["text"]
