name = "DeepSeek Flash Latest"
family = "deepseek-flash"
release_date = "2026-09-14"
last_updated = "2026-09-14"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.0001
output = 0.6
cache_read = 0.005

[limit]
context = 1_048_576
output = 943_718

[modalities]
input = ["text", "image"]
output = ["text"]
