temperature = true
tool_call = true
structured_output = true

[extends]
from = "minimax/MiniMax-M2.5"
omit = ["cost.cache_write"]

[interleaved]
field = "reasoning_details"

[cost]
input = 0.27
output = 1.08
cache_read = 0.027

[limit]
context = 200_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
