temperature = true
tool_call = true
structured_output = true

[extends]
from = "deepseek/deepseek-v4-flash"

[interleaved]
field = "reasoning_content"

[cost]
input = 0.07784
output = 0.15568
cache_read = 0.015568

[limit]
context = 1_024_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]
