temperature = true
tool_call = true
structured_output = true

[extends]
from = "deepseek/deepseek-v4-pro"

[interleaved]
field = "reasoning_content"

[cost]
input = 0.647106
output = 1.294212
cache_read = 0.053926

[limit]
context = 1_024_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]
