attachment = false
temperature = true
tool_call = true
structured_output = true

[extends]
from = "deepseek/deepseek-chat"
omit = ["cost.cache_read"]

[cost]
input = 0.2574
output = 1.0287

[limit]
context = 128_000
output = 16_000

[modalities]
input = ["text"]
output = ["text"]
