temperature = true
tool_call = true
structured_output = true

[extends]
from = "deepseek/deepseek-v4-pro"

[interleaved]
field = "reasoning_content"

[cost]
input = 0.422298
output = 0.844596
cache_read = 0.035192

[limit]
context = 1_024_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]
