temperature = true
tool_call = true
structured_output = true

[extends]
from = "deepseek/deepseek-v4-pro"

[interleaved]
field = "reasoning_content"

[cost]
input = 0.839724
output = 1.679448
cache_read = 0.069977

[limit]
context = 1_024_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]
