name = "GPT-4.1 (batch)"
family = "gpt"
release_date = "2025-04-14"
last_updated = "2025-04-14"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-06-30"
open_weights = false

[cost]
input = 1
output = 4
cache_read = 0.25

[limit]
context = 1_047_576
output = 32_768

[modalities]
input = ["image", "text", "pdf"]
output = ["text"]
